name: IpynbConvert

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://fereria/nbconvert:latest
    steps:
      - name: Git config
        run: |
          git config --global core.symlinks true
          git config --global user.name "Megumi Ando"
          git config --global user.email "remiria@flame-daybreak.net"
      - uses: actions/checkout@master
      - name: Convert Ipynb to Markdown
        run: python ipynb_convert.py
      - name: push
        run: |
          git add articles/*.md
          git commit -m "add md" -a
          git push
